# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Deploy pipeline

on:
  push:
    branches: [ pipeline ]
  pull_request:
    branches: [ pipeline ]

jobs:
  ano:
    name: Ano
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: sudo supervisorctl reload
#  deploy:
#    name: Deploy
#    runs-on: ubuntu-latest
#    steps:
#    - uses: actions/checkout@v2
#    - name: Upload ftp
#      uses: sebastianpopp/ftp-action@releases/v2
#      with:
#        host: ${{ secrets.FTP_SERVER }}
#        user: ${{ secrets.FTP_USERNAME }}
#        password: ${{ secrets.FTP_PASSWORD }}
#        localDir: "."
#        remoteDir: "/home/xhajdukp/"
